import type { Metadata } from "next";
import { Geist, Geist_Mono } from "next/font/google";
import "./global.scss";
import { Menu } from "./components/{parts}/menu";

const geistSans = Geist({
  variable: "--font-geist-sans",
  subsets: ["latin"],
});

const geistMono = Geist_Mono({
  variable: "--font-geist-mono",
  subsets: ["latin"],
});

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="pt-br">
      <body className='body'>
        <Menu/>
        {children}
      </body>
    </html>
  );
}
